apiVersion: v1
kind: Secret
metadata:
  name: meetly-secrets
  namespace: meetly
type: Opaque
stringData:
  POSTGRES_PASSWORD: "d70588a59bbe5e132131c255b692d14207baa18b7d6aafefb943862c7be032e4"
  NEXTAUTH_SECRET: "7RQrz0sCZbEEgjHYG8wKF2wtWE56sUqdU/E3sg4HoTs="
  CALENDSO_ENCRYPTION_KEY: "d740cc894facdcee9c7ee4445dc9abcb"
  EMAIL_SERVER_PASSWORD: "bskSkOPLF4ziny5"
  GOOGLE_API_CREDENTIALS: '{"web":{"client_id":"125460343424-rum6l0odal1qcqchbf1o8cc28jkpmauf.apps.googleusercontent.com","project_id":"odoo-calender-166504","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["https://meetly.rocket.re-cloud.io/api/integrations/googlecalendar/callback","https://meetly.rocket.re-cloud.io/api/auth/callback/google"]}}'
