apiVersion: v1
kind: ConfigMap
metadata:
  name: meetly-config
  namespace: meetly
data:
  POSTGRES_USER: "calcom"
  POSTGRES_DB: "calendso"
  NEXT_PUBLIC_WEBAPP_URL: "https://meetly.rocket.re-cloud.io"
  NEXTAUTH_URL: "https://meetly.rocket.re-cloud.io"
  CALCOM_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_LICENSE_CONSENT: "agree"
  ALLOWED_HOSTNAMES: '"meetly.rocket.re-cloud.io"'
  EMAIL_FROM: "meetly@re-cloud.io"
  EMAIL_FROM_NAME: "Meetly by Re:Cloud"
  EMAIL_SERVER_HOST: "smtp-relay.brevo.com"
  EMAIL_SERVER_PORT: "587"
  EMAIL_SERVER_USER: "sysadmin@euroblaze.de"
  TZ: "Europe/Berlin"
